### ISSUE TITLE
Phase 2: Design and Prototyping

### ISSUE THREAD

**Issue by f-allian** [RSE-Sheffield/SORT#4]
- [x] Design database structure
- [x] Create views to handle the app's logic
- [x] Trial Django’s templating system for rendering HTML outputs
- [ ] Handle form data and validation using Django's forms
- [ ] Create appropriate test suites
- [ ] Consider deployment strategies (e.g. Apache or other servers)
- [ ] Containerisation?
- [ ] Develop any CI/CD workflows
- [ ] Implement any security strategies
- [ ] Write the necessary documentation for users and future developers (README etc)
